/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Layout1: typeof import('./components/Layout1.vue')['default']
    Layout2: typeof import('./components/Layout2.vue')['default']
    Memo: typeof import('./components/Memo.vue')['default']
    Paper: typeof import('./components/Paper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./components/Timeline.vue')['default']
    WebsiteList: typeof import('./components/WebsiteList.vue')['default']
  }
}
